### PR TITLE
Add Esri attribution.

### PR DESCRIPTION
**Pull request by rgwozdz**
Added Esri attribition to header and footer:

Koop-esri

### CODE REVIEW

**Comment by dmfenton** [comment]
typo in sponsored

**Comment by dmfenton** [comment]
Might a suggest a different approach? How about a large section on the main page that includes sponsors and then lists Esri and has the Esri logo. We can have a call to action to get in touch w/ us about becoming a sponsor.

**Comment by rgwozdz** [comment]
Like this?
Screen Shot 2019-09-16 at 10 53 07 AM

**Comment by dmfenton** [comment]
That looks good. Probably want to get some similar language on some of the other high traffic Koop repos.

**Pull request merged**
